#!/usr/bin/env -S node
import {
  Migration,
  MigrationCLI,
  addForeignKey,
  addUnique,
  col,
  createIndex,
  fn,
  lit,
  primaryKey,
} from '@prisma-next/postgres/migration';

export default class M extends Migration {
  override describe() {
    return {
      from: null,
      to: 'sha256:6b50e39254a19592f2733ab5f90125a875bb373345d7410dac2218bf72575f10',
    };
  }

  override get operations() {
    return [
      this.createTable({
        schema: 'public',
        table: 'contact',
        columns: [
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('description', 'text'),
          col('id', 'character(36)', { notNull: true }),
          col('occurredAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('patientId', 'text', { notNull: true }),
          col('practiceId', 'text', { notNull: true }),
          col('type', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'fileLink',
        columns: [
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('id', 'character(36)', { notNull: true }),
          col('label', 'text', { notNull: true }),
          col('practiceId', 'text', { notNull: true }),
          col('sessionId', 'text', { notNull: true }),
          col('url', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'label',
        columns: [
          col('color', 'text', { notNull: true }),
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('id', 'character(36)', { notNull: true }),
          col('name', 'text', { notNull: true }),
          col('practiceId', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'patient',
        columns: [
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('email', 'text'),
          col('id', 'character(36)', { notNull: true }),
          col('name', 'text', { notNull: true }),
          col('phone', 'text'),
          col('practiceId', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'patientLabel',
        columns: [
          col('labelId', 'text', { notNull: true }),
          col('patientId', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['patientId', 'labelId'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'practice',
        columns: [
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('id', 'character(36)', { notNull: true }),
          col('name', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'product',
        columns: [
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('description', 'text'),
          col('id', 'character(36)', { notNull: true }),
          col('name', 'text', { notNull: true }),
          col('practiceId', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'referral',
        columns: [
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('id', 'character(36)', { notNull: true }),
          col('patientId', 'text', { notNull: true }),
          col('practiceId', 'text', { notNull: true }),
          col('productId', 'text', { notNull: true }),
          col('sessionId', 'text', { notNull: true }),
          col('sold', 'bool', { notNull: true }),
          col('soldAt', 'timestamptz'),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'reminder',
        columns: [
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('description', 'text'),
          col('id', 'character(36)', { notNull: true }),
          col('patientId', 'text', { notNull: true }),
          col('practiceId', 'text', { notNull: true }),
          col('resolvedAt', 'timestamptz'),
          col('status', 'text', { notNull: true, default: lit('pending') }),
          col('targetDate', 'timestamptz', { notNull: true }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'session',
        columns: [
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('id', 'character(36)', { notNull: true }),
          col('occurredAt', 'timestamptz'),
          col('patientId', 'text', { notNull: true }),
          col('practiceId', 'text', { notNull: true }),
          col('scheduledAt', 'timestamptz'),
          col('status', 'text', { notNull: true, default: lit('completed') }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'sessionAnnotation',
        columns: [
          col('content', 'text', { notNull: true }),
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('id', 'character(36)', { notNull: true }),
          col('practiceId', 'text', { notNull: true }),
          col('recordedAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('sessionId', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'sessionLabel',
        columns: [
          col('labelId', 'text', { notNull: true }),
          col('sessionId', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['sessionId', 'labelId'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'user',
        columns: [
          col('createdAt', 'timestamptz', { notNull: true, default: fn('now()') }),
          col('email', 'text', { notNull: true }),
          col('id', 'character(36)', { notNull: true }),
          col('name', 'text', { notNull: true }),
          col('passwordHash', 'text', { notNull: true }),
          col('practiceId', 'text', { notNull: true }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      addUnique('public', 'label', 'label_practiceId_name_key', ['practiceId', 'name']),
      addUnique('public', 'user', 'user_email_key', ['email']),
      createIndex('public', 'contact', 'contact_practiceId_idx', ['practiceId']),
      createIndex('public', 'contact', 'contact_patientId_idx', ['patientId']),
      createIndex('public', 'fileLink', 'fileLink_practiceId_idx', ['practiceId']),
      createIndex('public', 'fileLink', 'fileLink_sessionId_idx', ['sessionId']),
      createIndex('public', 'label', 'label_practiceId_idx', ['practiceId']),
      createIndex('public', 'patient', 'patient_practiceId_idx', ['practiceId']),
      createIndex('public', 'patientLabel', 'patientLabel_patientId_idx', ['patientId']),
      createIndex('public', 'patientLabel', 'patientLabel_labelId_idx', ['labelId']),
      createIndex('public', 'product', 'product_practiceId_idx', ['practiceId']),
      createIndex('public', 'referral', 'referral_practiceId_idx', ['practiceId']),
      createIndex('public', 'referral', 'referral_sessionId_idx', ['sessionId']),
      createIndex('public', 'referral', 'referral_patientId_idx', ['patientId']),
      createIndex('public', 'referral', 'referral_productId_idx', ['productId']),
      createIndex('public', 'reminder', 'reminder_practiceId_idx', ['practiceId']),
      createIndex('public', 'reminder', 'reminder_patientId_idx', ['patientId']),
      createIndex('public', 'session', 'session_practiceId_idx', ['practiceId']),
      createIndex('public', 'session', 'session_patientId_idx', ['patientId']),
      createIndex('public', 'sessionAnnotation', 'sessionAnnotation_practiceId_idx', [
        'practiceId',
      ]),
      createIndex('public', 'sessionAnnotation', 'sessionAnnotation_sessionId_idx', ['sessionId']),
      createIndex('public', 'sessionLabel', 'sessionLabel_sessionId_idx', ['sessionId']),
      createIndex('public', 'sessionLabel', 'sessionLabel_labelId_idx', ['labelId']),
      createIndex('public', 'user', 'user_practiceId_idx', ['practiceId']),
      addForeignKey('public', 'contact', {
        name: 'contact_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'contact', {
        name: 'contact_patientId_fkey',
        columns: ['patientId'],
        references: { schema: 'public', table: 'patient', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'fileLink', {
        name: 'fileLink_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'fileLink', {
        name: 'fileLink_sessionId_fkey',
        columns: ['sessionId'],
        references: { schema: 'public', table: 'session', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'label', {
        name: 'label_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'patient', {
        name: 'patient_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'patientLabel', {
        name: 'patientLabel_patientId_fkey',
        columns: ['patientId'],
        references: { schema: 'public', table: 'patient', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'patientLabel', {
        name: 'patientLabel_labelId_fkey',
        columns: ['labelId'],
        references: { schema: 'public', table: 'label', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'product', {
        name: 'product_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'referral', {
        name: 'referral_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'referral', {
        name: 'referral_sessionId_fkey',
        columns: ['sessionId'],
        references: { schema: 'public', table: 'session', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'referral', {
        name: 'referral_patientId_fkey',
        columns: ['patientId'],
        references: { schema: 'public', table: 'patient', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'referral', {
        name: 'referral_productId_fkey',
        columns: ['productId'],
        references: { schema: 'public', table: 'product', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'reminder', {
        name: 'reminder_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'reminder', {
        name: 'reminder_patientId_fkey',
        columns: ['patientId'],
        references: { schema: 'public', table: 'patient', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'session', {
        name: 'session_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'session', {
        name: 'session_patientId_fkey',
        columns: ['patientId'],
        references: { schema: 'public', table: 'patient', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'sessionAnnotation', {
        name: 'sessionAnnotation_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'sessionAnnotation', {
        name: 'sessionAnnotation_sessionId_fkey',
        columns: ['sessionId'],
        references: { schema: 'public', table: 'session', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'sessionLabel', {
        name: 'sessionLabel_sessionId_fkey',
        columns: ['sessionId'],
        references: { schema: 'public', table: 'session', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'sessionLabel', {
        name: 'sessionLabel_labelId_fkey',
        columns: ['labelId'],
        references: { schema: 'public', table: 'label', columns: ['id'] },
        onDelete: 'cascade',
      }),
      addForeignKey('public', 'user', {
        name: 'user_practiceId_fkey',
        columns: ['practiceId'],
        references: { schema: 'public', table: 'practice', columns: ['id'] },
        onDelete: 'cascade',
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
